# Generated by Django 4.2.14 on 2025-06-29 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="question", name="mock_test",),
    ]
